FROM registry.access.redhat.com/ubi8/ubi:8.3
MAINTAINER sig-platform@spinnaker.io
COPY rosco-web/build/install/rosco /opt/rosco
COPY rosco-web/config              /opt/rosco
COPY halconfig/packer              /opt/rosco/config/packer

ENV KUSTOMIZE_VERSION=3.8.5
ENV PACKER_VERSION=1.6.6
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN yum check-update && \
    yum install -y gcc libffi-devel python3 epel-release && \
    yum install -y python3-pip && \
    yum install -y wget && \
    yum clean all

RUN pip3 install --upgrade pip && \
    python3 -m pip install ansible

WORKDIR /packer

RUN yum install -y java-11-openjdk-headless.x86_64 wget unzip curl git  openssl curl net-tools nettle && \
  wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && \
  unzip packer_${PACKER_VERSION}_linux_amd64.zip && \
  rm packer_${PACKER_VERSION}_linux_amd64.zip


RUN yum -y update

ENV PATH "/packer:$PATH"

# Install Helm 3
RUN wget https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get-helm-3 && \
  chmod +x get-helm-3 && \
  ./get-helm-3 && \
  rm get-helm-3 && \
  mv /usr/local/bin/helm /usr/local/bin/helm3

# Install Helm 2
#RUN wget https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get && chmod +x get && ./get &&  rm get



RUN mkdir kustomize && \
  curl -s -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz|\
  tar xvz -C kustomize/

ENV PATH "kustomize:$PATH"


RUN mkdir -p /opt/rosco/plugins
USER root
CMD ["/opt/rosco/bin/rosco"]
