name: Create Release on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Get previous tag
        id: get_previous_tag
        run: |
          last_tag=$(git describe --abbrev=0 --tags)
          echo "::set-output name=last_tag::$last_tag"

      - name: Determine RC number
        id: determine_rc_number
        run: |
          last_tag=$INPUT_LAST_TAG
          branch_name=$INPUT_BRANCH_NAME
          if [[ $last_tag =~ $branch_name-rc([0-9]+) ]]; then
            rc_number=$((RegExp.$1 + 1))
          else
            rc_number=1
          fi
          echo "::set-output name=rc_number::$rc_number"
        shell: bash
        env:
          INPUT_LAST_TAG: ${{ steps.get_previous_tag.outputs.last_tag }}
          INPUT_BRANCH_NAME: ${{ steps.get_branch_name.outputs.branch }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_branch_name.outputs.branch }}-rc${{ steps.determine_rc_number.outputs.rc_number }}
          release_name: "Branch: ${{ steps.get_branch_name.outputs.branch }} and tag: ${{ steps.get_branch_name.outputs.branch }}-rc${{ steps.determine_rc_number.outputs.rc_number }}"
          body: |
            This is an automatically generated release for PR ${{ github.event.pull_request.number }}.
            Add your release notes here.
          draft: false
          prerelease: false

      - name: Build code
        run: |
          # Insert your build commands here
          echo "Building code..."

        # Add any additional configuration for your build environment here
